# Generated by Django 6.0.2 on 2026-03-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languaje', models.CharField(help_text='Ingrese un lenguaje (p.ej: Inglés, Francés, Español)', max_length=200, unique=True)),
            ],
        ),
    ]
