# Generated by Django 6.0.2 on 2026-03-04 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_languaje'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languaje',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='languaje',
            new_name='language',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.language'),
        ),
    ]
