# Generated by Django 6.0.2 on 2026-03-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_languaje_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
    ]
